import "./globals.css";
import { MyProvider } from "./context";
import { SessionProvider } from "next-auth/react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <SessionProvider>
          <MyProvider>{children}</MyProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
